openapi: 3.0.0
info:
  description: Api Documentation
  version: 0.1.0
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Auth
servers:
  - url: /localhost

paths:
  /api/auth/sign-in:
    post:
      tags:
        - Auth
      summary: signIn
      operationId: signIn
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    User:
      description: user
      type: object
      properties:
        username:
          type: string
        email:
          type: string

    ProjectAttributeType:
      type: string
      enum:
        - INTEGRATION
        - MESSENGER_BOT
        - BACKEND
        - FRONTEND
        - MOBILE_APP
