openapi: 3.0.0
info:
  description: Api Documentation
  version: 0.1.0
  title: Api Documentation
  termsOfService: urn:tos
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Auth
servers:
  - url: /localhost

paths:
  /api/auth/sign-in:
    post:
      tags:
        - Auth
      summary: signIn
      operationId: signIn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignInRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignInResponse'

  /api/auth/sign-up:
    post:
      tags:
        - Auth
      summary: signUp
      operationId: signUp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/SignUpRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SignUpResponse'
components:
  schemas:
    User:
      type: object
      properties:
        username:
          type: string
        email:
          type: string

    SignInResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string

    SignUpResponse:
      type: object
      properties:
        user:
          $ref: '#/components/schemas/User'
        token:
          type: string

    SignInRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    SignUpRequest:
      type: object
      properties:
        email:
          type: string
        password:
          type: string

    ProjectAttributeType:
      type: string
      enum:
        - INTEGRATION
        - MESSENGER_BOT
        - BACKEND
        - FRONTEND
        - MOBILE_APP
