openapi: 3.0.0
info:
  description: Api Documentation
  version: 0.1.0
  title: Workbench
  contact: {}
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0
tags:
  - name: Auth
servers:
  - url: /localhost

paths:
  /api/auth/sign-in:
    post:
      tags:
        - Auth
      summary: signIn
      operationId: signIn
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions/Account.yml#/SignInRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions/Account.yml#/SignInResponse'

  /api/auth/sign-up:
    post:
      tags:
        - Auth
      summary: signUp
      operationId: signUp
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions/Account.yml#/SignUpRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions/Account.yml#/SignUpResponse'

  /api/project:
    get:
      tags:
        - Project
      summary: getAllProjectsByUserId
      operationId: getAllProjectsByUserId
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: './definitions/Project.yml#/Project'
    post:
      tags:
        - Project
      summary: createProject
      operationId: createProject
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: './definitions/Project.yml#/ProjectCreationRequest'
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: './definitions/Project.yml#/Project'