ProjectCreationRequest:
  type: object
  properties:
    name:
      type: string
    description:
      type: string
    attributesIds:
      type: array
      items:
        type: integer
        format: int64

Project:
  type: object
  properties:
    id:
      type: integer
      format: int64
    name:
      type: string
    description:
      type: string
    roadmap:
      $ref: './Roadmap.yml#/Roadmap'

ProjectAttribute:
  type: object
  properties:
    id:
      type: integer
      format: int64
    attributeName:
      type: string
    taskTypes:
      type: array
      items:
        $ref: './TaskType.yml#/TaskType'
